[2024-06-18T17:38:44.936+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T17:38:44.975+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail manual__2024-06-18T11:53:38.240166+00:00 [queued]>
[2024-06-18T17:38:44.992+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail manual__2024-06-18T11:53:38.240166+00:00 [queued]>
[2024-06-18T17:38:44.993+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T17:38:45.058+0545] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-18 11:53:38.240166+00:00
[2024-06-18T17:38:45.063+0545] {standard_task_runner.py:63} INFO - Started process 26840 to run task
[2024-06-18T17:38:45.069+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'manual__2024-06-18T11:53:38.240166+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmpa4nbho87']
[2024-06-18T17:38:45.072+0545] {standard_task_runner.py:91} INFO - Job 131: Subtask send_mail
[2024-06-18T17:38:45.220+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail manual__2024-06-18T11:53:38.240166+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-18T17:38:45.551+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T11:53:38.240166+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T11:53:38.240166+00:00'
[2024-06-18T17:38:45.552+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T17:38:45.596+0545] {logging_mixin.py:188} WARNING - /home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-18T17:38:45.597+0545] {configuration.py:1050} WARNING - section/key [smtp/smtp_password] not found in config
[2024-06-18T17:38:45.598+0545] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-18T17:38:46.930+0545] {email.py:282} INFO - Sent an alert email to ['neupanesarika17@gmail.com']
[2024-06-18T17:38:48.443+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T17:38:48.444+0545] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 283, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/home/manisha/.pyenv/versions/3.10.14/lib/python3.10/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d9443c01a7336-1f855e55c47sm95785745ad.33 - gsmtp', 'samichi.rungta@gmail.com')
[2024-06-18T17:38:48.470+0545] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Backup_Database, task_id=send_mail, run_id=manual__2024-06-18T11:53:38.240166+00:00, execution_date=20240618T115338, start_date=20240618T115344, end_date=20240618T115348
[2024-06-18T17:38:48.675+0545] {standard_task_runner.py:110} ERROR - Failed to execute job 131 for task send_mail ((530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d9443c01a7336-1f855e55c47sm95785745ad.33 - gsmtp', 'samichi.rungta@gmail.com'); 26840)
[2024-06-18T17:38:48.700+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T17:38:48.746+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T17:38:48.749+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
