[2024-06-19T08:45:04.291+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T08:45:04.323+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:50:00+00:00 [queued]>
[2024-06-19T08:45:04.333+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:50:00+00:00 [queued]>
[2024-06-19T08:45:04.334+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-19T08:45:04.418+0545] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-19 02:50:00+00:00
[2024-06-19T08:45:04.425+0545] {standard_task_runner.py:63} INFO - Started process 16965 to run task
[2024-06-19T08:45:04.434+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'scheduled__2024-06-19T02:50:00+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmpgmxgnyjg']
[2024-06-19T08:45:04.438+0545] {standard_task_runner.py:91} INFO - Job 213: Subtask send_mail
[2024-06-19T08:45:04.601+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:50:00+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-19T08:45:04.866+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T02:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-19T02:50:00+00:00'
[2024-06-19T08:45:04.866+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T08:45:04.898+0545] {logging_mixin.py:188} WARNING - /home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-19T08:45:04.899+0545] {configuration.py:1050} WARNING - section/key [smtp/smtp_password] not found in config
[2024-06-19T08:45:04.899+0545] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-19T08:45:05.988+0545] {email.py:282} INFO - Sent an alert email to ['manishakhadka@peakvoyage.com']
[2024-06-19T08:45:07.013+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T08:45:07.015+0545] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 283, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/home/manisha/.pyenv/versions/3.10.14/lib/python3.10/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d2e1a72fcca58-705ccb3c2bbsm9961667b3a.98 - gsmtp', 'manishakhadka228@gmail.com')
[2024-06-19T08:45:07.060+0545] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Backup_Database, task_id=send_mail, run_id=scheduled__2024-06-19T02:50:00+00:00, execution_date=20240619T025000, start_date=20240619T030004, end_date=20240619T030007
[2024-06-19T08:45:07.162+0545] {standard_task_runner.py:110} ERROR - Failed to execute job 213 for task send_mail ((530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d2e1a72fcca58-705ccb3c2bbsm9961667b3a.98 - gsmtp', 'manishakhadka228@gmail.com'); 16965)
[2024-06-19T08:45:07.181+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T08:45:07.240+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T08:45:07.241+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-19T08:45:53.235+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T08:45:53.326+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:50:00+00:00 [queued]>
[2024-06-19T08:45:53.342+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:50:00+00:00 [queued]>
[2024-06-19T08:45:53.343+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-19T08:45:53.441+0545] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-19 02:50:00+00:00
[2024-06-19T08:45:53.450+0545] {standard_task_runner.py:63} INFO - Started process 17402 to run task
[2024-06-19T08:45:53.463+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'scheduled__2024-06-19T02:50:00+00:00', '--job-id', '217', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmp04ukydn1']
[2024-06-19T08:45:53.469+0545] {standard_task_runner.py:91} INFO - Job 217: Subtask send_mail
[2024-06-19T08:45:53.740+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:50:00+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-19T08:45:54.263+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T02:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-19T02:50:00+00:00'
[2024-06-19T08:45:54.264+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T08:45:54.322+0545] {logging_mixin.py:188} WARNING - /home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-19T08:45:54.322+0545] {configuration.py:1050} WARNING - section/key [smtp/smtp_password] not found in config
[2024-06-19T08:45:54.323+0545] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-19T08:45:55.761+0545] {email.py:282} INFO - Sent an alert email to ['manishakhadka@peakvoyage.com']
[2024-06-19T08:45:56.790+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T08:45:56.790+0545] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 283, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/home/manisha/.pyenv/versions/3.10.14/lib/python3.10/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError 41be03b00d2f7-6fee3c9f7b9sm8693144a12.86 - gsmtp', 'manishakhadka228@gmail.com')
[2024-06-19T08:45:56.808+0545] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Backup_Database, task_id=send_mail, run_id=scheduled__2024-06-19T02:50:00+00:00, execution_date=20240619T025000, start_date=20240619T030053, end_date=20240619T030056
[2024-06-19T08:45:57.023+0545] {standard_task_runner.py:110} ERROR - Failed to execute job 217 for task send_mail ((530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError 41be03b00d2f7-6fee3c9f7b9sm8693144a12.86 - gsmtp', 'manishakhadka228@gmail.com'); 17402)
[2024-06-19T08:45:57.051+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T08:45:57.092+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T08:45:57.094+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-19T08:49:15.504+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T08:49:15.551+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:50:00+00:00 [queued]>
[2024-06-19T08:49:15.563+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:50:00+00:00 [queued]>
[2024-06-19T08:49:15.563+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-19T08:49:15.690+0545] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-19 02:50:00+00:00
[2024-06-19T08:49:15.695+0545] {standard_task_runner.py:63} INFO - Started process 18945 to run task
[2024-06-19T08:49:15.701+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'scheduled__2024-06-19T02:50:00+00:00', '--job-id', '228', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmpdy99jn34']
[2024-06-19T08:49:15.704+0545] {standard_task_runner.py:91} INFO - Job 228: Subtask send_mail
[2024-06-19T08:49:15.903+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:50:00+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-19T08:49:16.700+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T02:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-19T02:50:00+00:00'
[2024-06-19T08:49:16.701+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T08:49:16.759+0545] {logging_mixin.py:188} WARNING - /home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-19T08:49:16.760+0545] {configuration.py:1050} WARNING - section/key [smtp/smtp_password] not found in config
[2024-06-19T08:49:16.761+0545] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-19T08:49:18.014+0545] {email.py:282} INFO - Sent an alert email to ['manishakhadka@peakvoyage.com']
[2024-06-19T08:49:19.036+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T08:49:19.037+0545] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 283, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/home/manisha/.pyenv/versions/3.10.14/lib/python3.10/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError 41be03b00d2f7-70ee5be7e00sm1580432a12.25 - gsmtp', 'manishakhadka228@gmail.com')
[2024-06-19T08:49:19.068+0545] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Backup_Database, task_id=send_mail, run_id=scheduled__2024-06-19T02:50:00+00:00, execution_date=20240619T025000, start_date=20240619T030415, end_date=20240619T030419
[2024-06-19T08:49:19.169+0545] {standard_task_runner.py:110} ERROR - Failed to execute job 228 for task send_mail ((530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError 41be03b00d2f7-70ee5be7e00sm1580432a12.25 - gsmtp', 'manishakhadka228@gmail.com'); 18945)
[2024-06-19T08:49:19.211+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T08:49:19.255+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T08:49:19.257+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
