[2024-06-18T13:41:47.972+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T13:41:48.009+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task manual__2024-06-18T07:56:46.527088+00:00 [queued]>
[2024-06-18T13:41:48.020+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task manual__2024-06-18T07:56:46.527088+00:00 [queued]>
[2024-06-18T13:41:48.022+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T13:41:48.105+0545] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 07:56:46.527088+00:00
[2024-06-18T13:41:48.114+0545] {standard_task_runner.py:63} INFO - Started process 15815 to run task
[2024-06-18T13:41:48.125+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'manual__2024-06-18T07:56:46.527088+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmp8l23fpfh']
[2024-06-18T13:41:48.130+0545] {standard_task_runner.py:91} INFO - Job 25: Subtask backup_task
[2024-06-18T13:41:48.290+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task manual__2024-06-18T07:56:46.527088+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-18T13:41:48.591+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T07:56:46.527088+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T07:56:46.527088+00:00'
[2024-06-18T13:41:48.593+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T13:41:48.625+0545] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T13:41:48.626+0545] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/root/backup.sh ']
[2024-06-18T13:41:48.632+0545] {subprocess.py:86} INFO - Output:
[2024-06-18T13:41:48.633+0545] {subprocess.py:93} INFO - /usr/bin/bash: line 1: /root/backup.sh: Permission denied
[2024-06-18T13:41:48.633+0545] {subprocess.py:97} INFO - Command exited with return code 126
[2024-06-18T13:41:48.633+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T13:41:48.646+0545] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 126.
[2024-06-18T13:41:48.648+0545] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Backup_Database, task_id=backup_task, run_id=manual__2024-06-18T07:56:46.527088+00:00, execution_date=20240618T075646, start_date=20240618T075648, end_date=20240618T075648
[2024-06-18T13:41:48.735+0545] {standard_task_runner.py:110} ERROR - Failed to execute job 25 for task backup_task (Bash command failed. The command returned a non-zero exit code 126.; 15815)
[2024-06-18T13:41:48.779+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T13:41:48.825+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
