[2024-06-19T08:36:10.536+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T08:36:10.565+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:40:00+00:00 [queued]>
[2024-06-19T08:36:10.574+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:40:00+00:00 [queued]>
[2024-06-19T08:36:10.574+0545] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-19T08:36:10.660+0545] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-19 02:40:00+00:00
[2024-06-19T08:36:10.667+0545] {standard_task_runner.py:63} INFO - Started process 12581 to run task
[2024-06-19T08:36:10.675+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'scheduled__2024-06-19T02:40:00+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmpyneazd39']
[2024-06-19T08:36:10.680+0545] {standard_task_runner.py:91} INFO - Job 186: Subtask send_mail
[2024-06-19T08:36:10.822+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:40:00+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-19T08:36:10.982+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T02:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-19T02:40:00+00:00'
[2024-06-19T08:36:10.983+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T08:36:11.015+0545] {logging_mixin.py:188} WARNING - /home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-19T08:36:11.016+0545] {configuration.py:1050} WARNING - section/key [smtp/smtp_password] not found in config
[2024-06-19T08:36:11.016+0545] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-19T08:36:12.186+0545] {email.py:282} INFO - Sent an alert email to ['manishakhadka@peakvoyage.com']
[2024-06-19T08:36:13.207+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T08:36:13.209+0545] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 283, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/home/manisha/.pyenv/versions/3.10.14/lib/python3.10/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d9443c01a7336-1f989ca342csm25109945ad.265 - gsmtp', 'manishakhadka228@gmail.com')
[2024-06-19T08:36:13.250+0545] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Backup_Database, task_id=send_mail, run_id=scheduled__2024-06-19T02:40:00+00:00, execution_date=20240619T024000, start_date=20240619T025110, end_date=20240619T025113
[2024-06-19T08:36:13.430+0545] {standard_task_runner.py:110} ERROR - Failed to execute job 186 for task send_mail ((530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d9443c01a7336-1f989ca342csm25109945ad.265 - gsmtp', 'manishakhadka228@gmail.com'); 12581)
[2024-06-19T08:36:13.462+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T08:36:13.495+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T08:36:13.496+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-19T08:37:37.824+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T08:37:37.900+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:40:00+00:00 [queued]>
[2024-06-19T08:37:37.916+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:40:00+00:00 [queued]>
[2024-06-19T08:37:37.917+0545] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-19T08:37:38.150+0545] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-19 02:40:00+00:00
[2024-06-19T08:37:38.165+0545] {standard_task_runner.py:63} INFO - Started process 13854 to run task
[2024-06-19T08:37:38.175+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'scheduled__2024-06-19T02:40:00+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmp7f11o5zn']
[2024-06-19T08:37:38.181+0545] {standard_task_runner.py:91} INFO - Job 193: Subtask send_mail
[2024-06-19T08:37:38.438+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:40:00+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-19T08:37:38.870+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T02:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-19T02:40:00+00:00'
[2024-06-19T08:37:38.874+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T08:37:38.985+0545] {logging_mixin.py:188} WARNING - /home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-19T08:37:38.986+0545] {configuration.py:1050} WARNING - section/key [smtp/smtp_password] not found in config
[2024-06-19T08:37:38.988+0545] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-19T08:37:40.118+0545] {email.py:282} INFO - Sent an alert email to ['manishakhadka@peakvoyage.com']
[2024-06-19T08:37:41.144+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T08:37:41.145+0545] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 283, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/home/manisha/.pyenv/versions/3.10.14/lib/python3.10/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d9443c01a7336-1f855ee83dasm105209125ad.173 - gsmtp', 'manishakhadka228@gmail.com')
[2024-06-19T08:37:41.168+0545] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Backup_Database, task_id=send_mail, run_id=scheduled__2024-06-19T02:40:00+00:00, execution_date=20240619T024000, start_date=20240619T025237, end_date=20240619T025241
[2024-06-19T08:37:41.436+0545] {standard_task_runner.py:110} ERROR - Failed to execute job 193 for task send_mail ((530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d9443c01a7336-1f855ee83dasm105209125ad.173 - gsmtp', 'manishakhadka228@gmail.com'); 13854)
[2024-06-19T08:37:41.488+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T08:37:41.586+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T08:37:41.590+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-19T08:40:40.489+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T08:40:40.550+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:40:00+00:00 [queued]>
[2024-06-19T08:40:40.565+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:40:00+00:00 [queued]>
[2024-06-19T08:40:40.565+0545] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-19T08:40:40.639+0545] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-19 02:40:00+00:00
[2024-06-19T08:40:40.643+0545] {standard_task_runner.py:63} INFO - Started process 15234 to run task
[2024-06-19T08:40:40.648+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'scheduled__2024-06-19T02:40:00+00:00', '--job-id', '201', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmp7zvy210u']
[2024-06-19T08:40:40.650+0545] {standard_task_runner.py:91} INFO - Job 201: Subtask send_mail
[2024-06-19T08:40:40.803+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:40:00+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-19T08:40:41.052+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T02:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-19T02:40:00+00:00'
[2024-06-19T08:40:41.053+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T08:40:41.095+0545] {logging_mixin.py:188} WARNING - /home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-19T08:40:41.096+0545] {configuration.py:1050} WARNING - section/key [smtp/smtp_password] not found in config
[2024-06-19T08:40:41.096+0545] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-19T08:40:42.252+0545] {email.py:282} INFO - Sent an alert email to ['manishakhadka@peakvoyage.com']
[2024-06-19T08:40:43.275+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T08:40:43.276+0545] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 283, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/home/manisha/.pyenv/versions/3.10.14/lib/python3.10/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d9443c01a7336-1f855e6f8absm104733465ad.77 - gsmtp', 'manishakhadka228@gmail.com')
[2024-06-19T08:40:43.298+0545] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Backup_Database, task_id=send_mail, run_id=scheduled__2024-06-19T02:40:00+00:00, execution_date=20240619T024000, start_date=20240619T025540, end_date=20240619T025543
[2024-06-19T08:40:43.379+0545] {standard_task_runner.py:110} ERROR - Failed to execute job 201 for task send_mail ((530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d9443c01a7336-1f855e6f8absm104733465ad.77 - gsmtp', 'manishakhadka228@gmail.com'); 15234)
[2024-06-19T08:40:43.392+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T08:40:43.416+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T08:40:43.417+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-19T08:43:14.487+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T08:43:14.566+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:40:00+00:00 [queued]>
[2024-06-19T08:43:14.578+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:40:00+00:00 [queued]>
[2024-06-19T08:43:14.579+0545] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-19T08:43:14.652+0545] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-19 02:40:00+00:00
[2024-06-19T08:43:14.657+0545] {standard_task_runner.py:63} INFO - Started process 16253 to run task
[2024-06-19T08:43:14.664+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'scheduled__2024-06-19T02:40:00+00:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmpv8zbrzuc']
[2024-06-19T08:43:14.668+0545] {standard_task_runner.py:91} INFO - Job 209: Subtask send_mail
[2024-06-19T08:43:14.808+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:40:00+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-19T08:43:15.011+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T02:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-19T02:40:00+00:00'
[2024-06-19T08:43:15.012+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T08:43:15.040+0545] {logging_mixin.py:188} WARNING - /home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-19T08:43:15.040+0545] {configuration.py:1050} WARNING - section/key [smtp/smtp_password] not found in config
[2024-06-19T08:43:15.040+0545] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-19T08:43:16.108+0545] {email.py:282} INFO - Sent an alert email to ['manishakhadka@peakvoyage.com']
[2024-06-19T08:43:17.032+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T08:43:17.034+0545] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 283, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/home/manisha/.pyenv/versions/3.10.14/lib/python3.10/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d9443c01a7336-1f9a5f7efccsm10554785ad.41 - gsmtp', 'manishakhadka228@gmail.com')
[2024-06-19T08:43:17.049+0545] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Backup_Database, task_id=send_mail, run_id=scheduled__2024-06-19T02:40:00+00:00, execution_date=20240619T024000, start_date=20240619T025814, end_date=20240619T025817
[2024-06-19T08:43:17.159+0545] {standard_task_runner.py:110} ERROR - Failed to execute job 209 for task send_mail ((530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d9443c01a7336-1f9a5f7efccsm10554785ad.41 - gsmtp', 'manishakhadka228@gmail.com'); 16253)
[2024-06-19T08:43:17.206+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T08:43:17.234+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T08:43:17.238+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
