[2024-06-19T08:36:38.922+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T08:36:38.967+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail manual__2024-06-19T02:51:33.329769+00:00 [queued]>
[2024-06-19T08:36:38.985+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail manual__2024-06-19T02:51:33.329769+00:00 [queued]>
[2024-06-19T08:36:38.985+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-19T08:36:39.088+0545] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-19 02:51:33.329769+00:00
[2024-06-19T08:36:39.092+0545] {standard_task_runner.py:63} INFO - Started process 13224 to run task
[2024-06-19T08:36:39.101+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'manual__2024-06-19T02:51:33.329769+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmpqirwgecl']
[2024-06-19T08:36:39.104+0545] {standard_task_runner.py:91} INFO - Job 192: Subtask send_mail
[2024-06-19T08:36:39.294+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail manual__2024-06-19T02:51:33.329769+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-19T08:36:39.586+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T02:51:33.329769+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-19T02:51:33.329769+00:00'
[2024-06-19T08:36:39.587+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T08:36:39.628+0545] {logging_mixin.py:188} WARNING - /home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-19T08:36:39.629+0545] {configuration.py:1050} WARNING - section/key [smtp/smtp_password] not found in config
[2024-06-19T08:36:39.629+0545] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-19T08:36:40.755+0545] {email.py:282} INFO - Sent an alert email to ['manishakhadka@peakvoyage.com']
[2024-06-19T08:36:41.785+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T08:36:41.787+0545] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 283, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/home/manisha/.pyenv/versions/3.10.14/lib/python3.10/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d2e1a72fcca58-705cc987738sm9661079b3a.89 - gsmtp', 'manishakhadka228@gmail.com')
[2024-06-19T08:36:41.832+0545] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Backup_Database, task_id=send_mail, run_id=manual__2024-06-19T02:51:33.329769+00:00, execution_date=20240619T025133, start_date=20240619T025138, end_date=20240619T025141
[2024-06-19T08:36:41.951+0545] {standard_task_runner.py:110} ERROR - Failed to execute job 192 for task send_mail ((530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d2e1a72fcca58-705cc987738sm9661079b3a.89 - gsmtp', 'manishakhadka228@gmail.com'); 13224)
[2024-06-19T08:36:42.007+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T08:36:42.068+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T08:36:42.070+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
