[2024-06-18T14:29:55.904+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T14:29:55.949+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task manual__2024-06-18T08:43:51.095121+00:00 [queued]>
[2024-06-18T14:29:55.959+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task manual__2024-06-18T08:43:51.095121+00:00 [queued]>
[2024-06-18T14:29:55.960+0545] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T14:29:56.154+0545] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 08:43:51.095121+00:00
[2024-06-18T14:29:56.156+0545] {standard_task_runner.py:63} INFO - Started process 18533 to run task
[2024-06-18T14:29:56.160+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'manual__2024-06-18T08:43:51.095121+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmpnxj2p73z']
[2024-06-18T14:29:56.162+0545] {standard_task_runner.py:91} INFO - Job 54: Subtask backup_task
[2024-06-18T14:29:56.457+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task manual__2024-06-18T08:43:51.095121+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-18T14:29:56.649+0545] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'backup_task', field 'bash_command'. Template: '/home/manisha/airflow/bashScripts/backup.sh'
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /home/manisha/airflow/bashScripts/backup.sh
[2024-06-18T14:29:56.650+0545] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1337, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /home/manisha/airflow/bashScripts/backup.sh
[2024-06-18T14:29:56.664+0545] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Backup_Database, task_id=backup_task, run_id=manual__2024-06-18T08:43:51.095121+00:00, execution_date=20240618T084351, start_date=20240618T084455, end_date=20240618T084456
[2024-06-18T14:29:56.901+0545] {standard_task_runner.py:110} ERROR - Failed to execute job 54 for task backup_task (/home/manisha/airflow/bashScripts/backup.sh; 18533)
[2024-06-18T14:29:56.935+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T14:29:56.963+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T14:29:57.119+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
