[2024-06-19T08:26:03.562+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T08:26:03.599+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:30:00+00:00 [queued]>
[2024-06-19T08:26:03.607+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:30:00+00:00 [queued]>
[2024-06-19T08:26:03.607+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-19T08:26:03.676+0545] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-19 02:30:00+00:00
[2024-06-19T08:26:03.682+0545] {standard_task_runner.py:63} INFO - Started process 3754 to run task
[2024-06-19T08:26:03.690+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'scheduled__2024-06-19T02:30:00+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmptfuudyg0']
[2024-06-19T08:26:03.694+0545] {standard_task_runner.py:91} INFO - Job 171: Subtask send_mail
[2024-06-19T08:26:03.858+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:30:00+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-19T08:26:04.142+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-19T02:30:00+00:00'
[2024-06-19T08:26:04.143+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T08:26:04.172+0545] {logging_mixin.py:188} WARNING - /home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-19T08:26:04.172+0545] {configuration.py:1050} WARNING - section/key [smtp/smtp_password] not found in config
[2024-06-19T08:26:04.173+0545] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-19T08:26:06.001+0545] {email.py:282} INFO - Sent an alert email to ['manishakhadka@peakvoyage.com']
[2024-06-19T08:26:07.019+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T08:26:07.021+0545] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 283, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/home/manisha/.pyenv/versions/3.10.14/lib/python3.10/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d9443c01a7336-1f855e55dd8sm104851315ad.58 - gsmtp', 'manishakhadka228@gmail.com')
[2024-06-19T08:26:07.136+0545] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Backup_Database, task_id=send_mail, run_id=scheduled__2024-06-19T02:30:00+00:00, execution_date=20240619T023000, start_date=20240619T024103, end_date=20240619T024107
[2024-06-19T08:26:07.208+0545] {standard_task_runner.py:110} ERROR - Failed to execute job 171 for task send_mail ((530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d9443c01a7336-1f855e55dd8sm104851315ad.58 - gsmtp', 'manishakhadka228@gmail.com'); 3754)
[2024-06-19T08:26:07.247+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T08:26:07.300+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T08:26:07.302+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-19T08:28:37.762+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T08:28:37.794+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:30:00+00:00 [queued]>
[2024-06-19T08:28:37.801+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:30:00+00:00 [queued]>
[2024-06-19T08:28:37.801+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-19T08:28:37.852+0545] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-19 02:30:00+00:00
[2024-06-19T08:28:37.859+0545] {standard_task_runner.py:63} INFO - Started process 6753 to run task
[2024-06-19T08:28:37.867+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'scheduled__2024-06-19T02:30:00+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmp_d3pd03y']
[2024-06-19T08:28:37.872+0545] {standard_task_runner.py:91} INFO - Job 175: Subtask send_mail
[2024-06-19T08:28:38.032+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T02:30:00+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-19T08:28:38.284+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-19T02:30:00+00:00'
[2024-06-19T08:28:38.285+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T08:28:38.316+0545] {logging_mixin.py:188} WARNING - /home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-19T08:28:38.316+0545] {configuration.py:1050} WARNING - section/key [smtp/smtp_password] not found in config
[2024-06-19T08:28:38.317+0545] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-19T08:28:39.519+0545] {email.py:282} INFO - Sent an alert email to ['manishakhadka@peakvoyage.com']
[2024-06-19T08:28:40.641+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T08:28:40.644+0545] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 283, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/home/manisha/.pyenv/versions/3.10.14/lib/python3.10/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d2e1a72fcca58-705cc9744ddsm9661026b3a.71 - gsmtp', 'manishakhadka228@gmail.com')
[2024-06-19T08:28:40.684+0545] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Backup_Database, task_id=send_mail, run_id=scheduled__2024-06-19T02:30:00+00:00, execution_date=20240619T023000, start_date=20240619T024337, end_date=20240619T024340
[2024-06-19T08:28:40.781+0545] {standard_task_runner.py:110} ERROR - Failed to execute job 175 for task send_mail ((530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d2e1a72fcca58-705cc9744ddsm9661026b3a.71 - gsmtp', 'manishakhadka228@gmail.com'); 6753)
[2024-06-19T08:28:40.818+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T08:28:40.868+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
