[2024-06-18T14:32:55.601+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T14:32:55.646+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task manual__2024-06-18T08:47:53.502392+00:00 [queued]>
[2024-06-18T14:32:55.659+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task manual__2024-06-18T08:47:53.502392+00:00 [queued]>
[2024-06-18T14:32:55.660+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T14:32:55.874+0545] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 08:47:53.502392+00:00
[2024-06-18T14:32:55.884+0545] {standard_task_runner.py:63} INFO - Started process 18618 to run task
[2024-06-18T14:32:55.894+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'manual__2024-06-18T08:47:53.502392+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmp6nvuzh6u']
[2024-06-18T14:32:55.901+0545] {standard_task_runner.py:91} INFO - Job 56: Subtask backup_task
[2024-06-18T14:32:56.298+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task manual__2024-06-18T08:47:53.502392+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-18T14:32:56.584+0545] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'backup_task', field 'bash_command'. Template: '/home/manisha/airflow/bashScripts/backup.sh'
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /home/manisha/airflow/bashScripts/backup.sh
[2024-06-18T14:32:56.585+0545] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1337, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /home/manisha/airflow/bashScripts/backup.sh
[2024-06-18T14:32:56.601+0545] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Backup_Database, task_id=backup_task, run_id=manual__2024-06-18T08:47:53.502392+00:00, execution_date=20240618T084753, start_date=20240618T084755, end_date=20240618T084756
[2024-06-18T14:32:56.744+0545] {standard_task_runner.py:110} ERROR - Failed to execute job 56 for task backup_task (/home/manisha/airflow/bashScripts/backup.sh; 18618)
[2024-06-18T14:32:56.789+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T14:32:56.852+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T14:32:56.853+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
