[2024-06-18T14:25:01.830+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T14:25:01.861+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T08:30:00+00:00 [queued]>
[2024-06-18T14:25:01.870+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T08:30:00+00:00 [queued]>
[2024-06-18T14:25:01.870+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T14:25:02.023+0545] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 08:30:00+00:00
[2024-06-18T14:25:02.030+0545] {standard_task_runner.py:63} INFO - Started process 17978 to run task
[2024-06-18T14:25:02.039+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'scheduled__2024-06-18T08:30:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmpmc8il4dk']
[2024-06-18T14:25:02.044+0545] {standard_task_runner.py:91} INFO - Job 47: Subtask backup_task
[2024-06-18T14:25:02.379+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T08:30:00+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-18T14:25:02.719+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T08:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T08:30:00+00:00'
[2024-06-18T14:25:02.720+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T14:25:02.739+0545] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T14:25:02.739+0545] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/root/backup.sh ']
[2024-06-18T14:25:02.749+0545] {subprocess.py:86} INFO - Output:
[2024-06-18T14:25:02.750+0545] {subprocess.py:93} INFO - /usr/bin/bash: line 1: /root/backup.sh: Permission denied
[2024-06-18T14:25:02.750+0545] {subprocess.py:97} INFO - Command exited with return code 126
[2024-06-18T14:25:02.751+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T14:25:02.768+0545] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 126.
[2024-06-18T14:25:02.772+0545] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Backup_Database, task_id=backup_task, run_id=scheduled__2024-06-18T08:30:00+00:00, execution_date=20240618T083000, start_date=20240618T084001, end_date=20240618T084002
[2024-06-18T14:25:02.881+0545] {standard_task_runner.py:110} ERROR - Failed to execute job 47 for task backup_task (Bash command failed. The command returned a non-zero exit code 126.; 17978)
[2024-06-18T14:25:02.894+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T14:25:02.910+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T14:28:49.674+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T14:28:49.784+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T08:30:00+00:00 [queued]>
[2024-06-18T14:28:49.792+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T08:30:00+00:00 [queued]>
[2024-06-18T14:28:49.792+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T14:28:50.068+0545] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 08:30:00+00:00
[2024-06-18T14:28:50.072+0545] {standard_task_runner.py:63} INFO - Started process 18369 to run task
[2024-06-18T14:28:50.077+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'scheduled__2024-06-18T08:30:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmpsr4l2y2v']
[2024-06-18T14:28:50.079+0545] {standard_task_runner.py:91} INFO - Job 51: Subtask backup_task
[2024-06-18T14:28:50.413+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T08:30:00+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-18T14:28:50.666+0545] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'backup_task', field 'bash_command'. Template: '/home/manisha/airflow/bashScripts/backup.sh'
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /home/manisha/airflow/bashScripts/backup.sh
[2024-06-18T14:28:50.667+0545] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1337, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /home/manisha/airflow/bashScripts/backup.sh
[2024-06-18T14:28:50.681+0545] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Backup_Database, task_id=backup_task, run_id=scheduled__2024-06-18T08:30:00+00:00, execution_date=20240618T083000, start_date=20240618T084349, end_date=20240618T084350
[2024-06-18T14:28:50.861+0545] {standard_task_runner.py:110} ERROR - Failed to execute job 51 for task backup_task (/home/manisha/airflow/bashScripts/backup.sh; 18369)
[2024-06-18T14:28:50.892+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T14:28:50.945+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T14:28:50.946+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T14:32:43.687+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T14:32:43.783+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T08:30:00+00:00 [queued]>
[2024-06-18T14:32:43.804+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T08:30:00+00:00 [queued]>
[2024-06-18T14:32:43.804+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T14:32:44.159+0545] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 08:30:00+00:00
[2024-06-18T14:32:44.163+0545] {standard_task_runner.py:63} INFO - Started process 18615 to run task
[2024-06-18T14:32:44.172+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'scheduled__2024-06-18T08:30:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmp3m3z4j8n']
[2024-06-18T14:32:44.176+0545] {standard_task_runner.py:91} INFO - Job 55: Subtask backup_task
[2024-06-18T14:32:44.657+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T08:30:00+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-18T14:32:44.961+0545] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'backup_task', field 'bash_command'. Template: '/home/manisha/airflow/bashScripts/backup.sh'
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /home/manisha/airflow/bashScripts/backup.sh
[2024-06-18T14:32:44.962+0545] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1337, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /home/manisha/airflow/bashScripts/backup.sh
[2024-06-18T14:32:44.978+0545] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Backup_Database, task_id=backup_task, run_id=scheduled__2024-06-18T08:30:00+00:00, execution_date=20240618T083000, start_date=20240618T084743, end_date=20240618T084744
[2024-06-18T14:32:45.654+0545] {standard_task_runner.py:110} ERROR - Failed to execute job 55 for task backup_task (/home/manisha/airflow/bashScripts/backup.sh; 18615)
[2024-06-18T14:32:45.672+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T14:32:45.737+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T14:32:45.739+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
