[2024-06-18T13:11:47.096+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T13:11:47.121+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T07:10:00+00:00 [queued]>
[2024-06-18T13:11:47.128+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T07:10:00+00:00 [queued]>
[2024-06-18T13:11:47.128+0545] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T13:11:47.193+0545] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 07:10:00+00:00
[2024-06-18T13:11:47.198+0545] {standard_task_runner.py:63} INFO - Started process 13087 to run task
[2024-06-18T13:11:47.204+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'scheduled__2024-06-18T07:10:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmpvbmx7mh7']
[2024-06-18T13:11:47.207+0545] {standard_task_runner.py:91} INFO - Job 17: Subtask backup_task
[2024-06-18T13:11:47.351+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T07:10:00+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-18T13:11:47.568+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T07:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T07:10:00+00:00'
[2024-06-18T13:11:47.570+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T13:11:47.604+0545] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T13:11:47.605+0545] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/root/backup.sh ']
[2024-06-18T13:11:47.611+0545] {subprocess.py:86} INFO - Output:
[2024-06-18T13:11:47.612+0545] {subprocess.py:93} INFO - /usr/bin/bash: line 1: /root/backup.sh: Permission denied
[2024-06-18T13:11:47.612+0545] {subprocess.py:97} INFO - Command exited with return code 126
[2024-06-18T13:11:47.621+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T13:11:47.635+0545] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 126.
[2024-06-18T13:11:47.639+0545] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Backup_Database, task_id=backup_task, run_id=scheduled__2024-06-18T07:10:00+00:00, execution_date=20240618T071000, start_date=20240618T072647, end_date=20240618T072647
[2024-06-18T13:11:47.713+0545] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task backup_task (Bash command failed. The command returned a non-zero exit code 126.; 13087)
[2024-06-18T13:11:47.737+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T13:11:47.778+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T13:11:47.826+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
