[2024-06-18T14:07:03.263+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T14:07:03.308+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T08:10:00+00:00 [queued]>
[2024-06-18T14:07:03.330+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T08:10:00+00:00 [queued]>
[2024-06-18T14:07:03.331+0545] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T14:07:03.530+0545] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 08:10:00+00:00
[2024-06-18T14:07:03.538+0545] {standard_task_runner.py:63} INFO - Started process 16991 to run task
[2024-06-18T14:07:03.545+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'scheduled__2024-06-18T08:10:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmpczftc0st']
[2024-06-18T14:07:03.548+0545] {standard_task_runner.py:91} INFO - Job 39: Subtask backup_task
[2024-06-18T14:07:03.796+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T08:10:00+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-18T14:07:04.139+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T08:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T08:10:00+00:00'
[2024-06-18T14:07:04.141+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T14:07:04.165+0545] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T14:07:04.166+0545] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/root/backup.sh ']
[2024-06-18T14:07:04.173+0545] {subprocess.py:86} INFO - Output:
[2024-06-18T14:07:04.174+0545] {subprocess.py:93} INFO - /usr/bin/bash: line 1: /root/backup.sh: Permission denied
[2024-06-18T14:07:04.174+0545] {subprocess.py:97} INFO - Command exited with return code 126
[2024-06-18T14:07:04.175+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T14:07:04.192+0545] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 126.
[2024-06-18T14:07:04.195+0545] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Backup_Database, task_id=backup_task, run_id=scheduled__2024-06-18T08:10:00+00:00, execution_date=20240618T081000, start_date=20240618T082203, end_date=20240618T082204
[2024-06-18T14:07:04.363+0545] {standard_task_runner.py:110} ERROR - Failed to execute job 39 for task backup_task (Bash command failed. The command returned a non-zero exit code 126.; 16991)
[2024-06-18T14:07:04.401+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T14:07:04.453+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T14:07:04.543+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
