[2024-06-18T17:57:26.829+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T17:57:26.869+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task manual__2024-06-18T12:12:25.545756+00:00 [queued]>
[2024-06-18T17:57:26.882+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task manual__2024-06-18T12:12:25.545756+00:00 [queued]>
[2024-06-18T17:57:26.883+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T17:57:26.959+0545] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 12:12:25.545756+00:00
[2024-06-18T17:57:26.967+0545] {standard_task_runner.py:63} INFO - Started process 28186 to run task
[2024-06-18T17:57:26.972+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'manual__2024-06-18T12:12:25.545756+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmp288om9mg']
[2024-06-18T17:57:26.976+0545] {standard_task_runner.py:91} INFO - Job 145: Subtask backup_task
[2024-06-18T17:57:27.137+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task manual__2024-06-18T12:12:25.545756+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-18T17:57:27.369+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T12:12:25.545756+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T12:12:25.545756+00:00'
[2024-06-18T17:57:27.369+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T17:57:27.394+0545] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T17:57:27.396+0545] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/manisha/airflow/bashScripts/backup.sh ']
[2024-06-18T17:57:27.406+0545] {subprocess.py:86} INFO - Output:
[2024-06-18T17:58:13.523+0545] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-06-18T17:58:13.523+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T17:58:13.537+0545] {process_utils.py:132} INFO - Sending 15 to group 28186. PIDs of all processes in the group: [28187, 28189, 28186]
[2024-06-18T17:58:13.537+0545] {process_utils.py:87} INFO - Sending the signal 15 to group 28186
[2024-06-18T17:58:13.538+0545] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-18T17:58:13.538+0545] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-06-18T17:58:13.539+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T17:58:13.751+0545] {process_utils.py:80} INFO - Process psutil.Process(pid=28186, status='terminated', exitcode=0, started='17:57:26') (28186) terminated with exit code 0
[2024-06-18T17:58:13.753+0545] {process_utils.py:80} INFO - Process psutil.Process(pid=28189, status='terminated', started='17:57:27') (28189) terminated with exit code None
[2024-06-18T17:58:13.754+0545] {process_utils.py:80} INFO - Process psutil.Process(pid=28187, status='terminated', started='17:57:27') (28187) terminated with exit code None
