[2024-06-18T13:46:02.577+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T13:46:02.603+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T07:50:00+00:00 [queued]>
[2024-06-18T13:46:02.609+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T07:50:00+00:00 [queued]>
[2024-06-18T13:46:02.610+0545] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T13:46:02.677+0545] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 07:50:00+00:00
[2024-06-18T13:46:02.683+0545] {standard_task_runner.py:63} INFO - Started process 16016 to run task
[2024-06-18T13:46:02.691+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'scheduled__2024-06-18T07:50:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmpu4wu_kb9']
[2024-06-18T13:46:02.695+0545] {standard_task_runner.py:91} INFO - Job 28: Subtask backup_task
[2024-06-18T13:46:02.864+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T07:50:00+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-18T13:46:03.012+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T07:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T07:50:00+00:00'
[2024-06-18T13:46:03.013+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T13:46:03.022+0545] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T13:46:03.023+0545] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/root/backup.sh ']
[2024-06-18T13:46:03.027+0545] {subprocess.py:86} INFO - Output:
[2024-06-18T13:46:03.028+0545] {subprocess.py:93} INFO - /usr/bin/bash: line 1: /root/backup.sh: Permission denied
[2024-06-18T13:46:03.028+0545] {subprocess.py:97} INFO - Command exited with return code 126
[2024-06-18T13:46:03.028+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T13:46:03.039+0545] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/manisha/airflow_env/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 126.
[2024-06-18T13:46:03.041+0545] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Backup_Database, task_id=backup_task, run_id=scheduled__2024-06-18T07:50:00+00:00, execution_date=20240618T075000, start_date=20240618T080102, end_date=20240618T080103
[2024-06-18T13:46:03.119+0545] {standard_task_runner.py:110} ERROR - Failed to execute job 28 for task backup_task (Bash command failed. The command returned a non-zero exit code 126.; 16016)
[2024-06-18T13:46:03.144+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T13:46:03.205+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T13:46:03.252+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
